# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language (English)
en:
  locale: en-us
  contentDir: content/en
  label: English
  weight: 1

# Spanish
es:
  locale: es
  contentDir: content/es
  label: Español
  weight: 2
  # title: Lee-Ann Vidal Covas, PhD
  params:
    description: Científica del lenguaje (PhD, Boston University) con experiencia en investigación sociolingüística, curación de conjuntos de datos y ciencia de datos aplicada.
