# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: Portfolio
    url: portfolio/
    weight: 11
  - name: Research
    url: /research/
    weight: 15
  - name: Coding Corner
    url: /coding_corner/
    weight: 17
  - name: Teaching & Training
    url: teaching/
    weight: 30
  - name: CV & Résumé
    url: experience/
    weight: 50
